import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

//import NavBar from "./components/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <Head>
        <link rel="icon" href="favicon.ico" />
        {/* You can also use a .png, .svg, etc. */}
      </Head>
      <body>
      
        {children}
      </body>
    </html>
  );
}
